### ISSUE TITLE
Sidebar Announcements Still Aren't Showing Up

### ISSUE THREAD

**Issue by kelnera** [osu-cass/cass-pelican#100]
@osu-cass/cass-web @leian7 @athai I've merged the sidebar announcement pr and just checked staging site and it's not showing up. (Blerg!) Do we know what's going on?

**Comment by athai** [comment]
@kelnera As far as I know, it *shouldn't* show up on the staging site (since it's been a while since we updated the dougfir-submodule). So rest assured, nothing's broken (I don't think!).

**Comment by kelnera** [comment]
@athai Okay that's what @Kennric was telling me earlier. As far as I know, there's nothing to announce, but we should keep working on this so it's ready to go if something suddenly comes up. No need to stress though.

**Comment by athai** [comment]
@Kennric Should I push an update for the submodule to staging? Or is there any reason we might want to hold off on that for now?
