### ISSUE TITLE
Enable Markdown

### ISSUE THREAD

**Issue by jldugger** [osu-cass/cass-pelican#112]
We've enabled markdown on osl-pelican. We should do the same for this repo.

It's a simple addition to the `requirements.txt` to add the library, then pages can be written in either markdown or restructured text as the author desires or requirements merit. Authors should note that the metadata format is slightly different between them:

http://docs.getpelican.com/en/3.6.3/content.html#file-metadata

**Comment by jldugger** [comment]
Staging currently doesn't build after a rebase intended to prep for merging into master. After #110 is merged, I'll open a PR to enable this.

**Comment by kelnera** [comment]
Wrong button.

**Comment by jldugger** [comment]
NO, thanks for the reminder.
