### ISSUE TITLE
Add student agreement

### ISSUE THREAD

**Issue by Kennric** [osu-cass/cass-pelican#15]
Pending approval and final version of the Student Agreement, add it to the site somewhere TBD.

https://docs.google.com/document/d/1zzm3YuI5NI6ulyotw3o7Yf8JgdTEgx_Tcw12rLQxNTg/edit#

@carlos-jensen @ramereth thoughts?

**Comment by hertelc** [comment]
@Kennric I like that idea.  I need to edit the version as we forgot to take "Draft" out of file... :)

**Comment by hertelc** [comment]
@Kennric we discussed this one in the CASS staff meeting today and decided to not post the student agreement on the public website.  I think we can close this one out.

**Comment by ramereth** [comment]
@Kennric Let's import our version into our internal docs site and close this.
