### ISSUE TITLE
Top header to match OSU guidelines

### ISSUE THREAD

**Issue by bielenpa** [osu-cass/cass-pelican#25]
This is from Rachel Robertson in EECS:
The top header does not match the COE template in color, spacing and font. You can use the EECS website as a comparison to how the template should look: http://eecs.oregonstate.edu/
@kelnera @Kennric

**Comment by leian7** [comment]
@bielenpa Does spacing refer to the width of the headers/width of all the content below the headers? And would Rachel Robertson also like to include the EECS website's blue background bar in our template?

**Comment by bielenpa** [comment]
@kelnera Is to meet with Rachel Robertson to find out exactly what needs to match.
@Kennric @leian7

**Comment by bielenpa** [comment]
**The word from the head honcho, Krista Klinkhammer, about one feature of the header:**
Krista,
I’m working with CASS on their website. Right now their top headers has School of Electrical Engineering and Computer Science: http://cass.oregonstate.edu/. Should it be College of Engineering instead?
-Rachel 
 Hi Rachel,
I think it should…that’s how things like the Wave Labhttp://wave.oregonstate.edu/ , Energy Efficiency Centerhttp://eec.oregonstate.edu/ , and Humanitarian Engineering http://humanitarian.engineering.oregonstate.edu/ have it set up. 
Thanks,
Krista

@kelnera @Kennric @leian7

**Comment by hertelc** [comment]
Are any of those actually under another department, or are they directly under College of Engineering?

Carrie Hertel, PMP
Software Dev Group & Test Lab Director
Center for Applied Systems & Software
Oregon State University

**Comment by leian7** [comment]
[This issue has been copied to our theme repo](https://github.com/osuosl/dougfir-pelican-theme/issues/44) and has an implemented fix [here](https://github.com/osuosl/dougfir-pelican-theme/pull/45).
