### ISSUE TITLE
OSL Updates

### ISSUE THREAD

**Issue by ramereth** [osu-cass/cass-pelican#27]
Here are some updates I can see we need on the OSL page:

* [ ] change 10 years to 13 years
* [ ] change _cloud solutions to academic, state and industry partners_ to _cloud solutions to academic and industry partners_
* [ ] change _Mailman, Drupal, Database as a service_ to _various web platforms, Mailman, Database as a service_
* [ ] Add a sentence at the bottom that basically states: _For more information, please visit the OSL website_ which includes a link to the website.

**Comment by hertelc** [comment]
Need to remove the BSG logo/link on the right hand side of the OSL page.
