### ISSUE TITLE
Feature request--Sidebar with the labs, etc.

### ISSUE THREAD

**Issue by bielenpa** [osu-cass/cass-pelican#31]
I would love to see a sidebar replace the one on the right (or put it on the left instead--Carlos says it's better on the left) showing each of the labs with an icon. 
OSL
Open Source Lab

SDG
Softeware Development Group

TL
Test Lab

Donate

@Kennric @kelnera

**Comment by hertelc** [comment]
I agree with the above and was just going to open a ticket that I miss having the labs shown on the right or left.

**Comment by bielenpa** [comment]
Change of lab names so it should read like this instead:

OSL
Open Source Lab

SDG
Softeware Development Group

IoT/TL
Internet of Things and Test Lab

Donate
@kelnera @Kennric
