### ISSUE TITLE
Update staff and students lists

### ISSUE THREAD

**Issue by matthewrsj** [osu-cass/cass-pelican#4]
* jme and maybe others need to be removed
* On the OSL side, there are several sysadmin students that need to be added
 - Kenny Steinfeldt
 - Chris Keltz
 - Spencer Moss

**Comment by hertelc** [comment]
I am trying to take care of the Staff page removals.  Need permissions to be able to publish changes.  Otherwise should be ready for review once that happens.

**Comment by hertelc** [comment]
Looks like the staff page is now updated.  Student page is still needing changes.  @kelnera - I think you have another issue for tracking this and we can close this one?
