### ISSUE TITLE
Correct contact info in the footer

### ISSUE THREAD

**Issue by Kennric** [osu-cass/cass-pelican#46]
The footer contains contact info for OSL, not CASS. Get the correct CASS info and replace.

**Comment by bielenpa** [comment]
This should be the correct contact info:

Center for Applied Systems and Software--CASS
209 & 224 Milne Computer Center
1800 SW Campus Way
Corvallis, OR 97331
info@CASS.oregonstate.edu
Phone: 547-737-2060

@Kennric @kelnera

**Comment by alxngyn** [comment]
I put a fix in here:
https://github.com/osuosl/dougfir-pelican-theme/pull/33
