### ISSUE TITLE
Remove deprecated/incomplete/paused projects from Services Page

### ISSUE THREAD

**Issue by ramereth** [osu-cass/cass-pelican#49]
Please remove the following sections from the Projects page:

* [x] Ganeti Web Manager
* [x] ORVSD
* [x] IPMI
* [x] Fenestra
* [x] Supercell

In addition, please add a link to the CS312 website: http://cs312.osuosl.org.

**Comment by hertelc** [comment]
I'm going to take a stab at this one

**Comment by kelnera** [comment]
Before you remove things, I had a meeting with Pam and Rachel and Rachel
thinks it would be better to have the projects list be a list of projects
we've worked on in the past and have more substance than say a list of
projects that are just getting on their feet or current projects that we
can only sort of talk about for privacy reasons. Thoughts?

**Comment by hertelc** [comment]
@kelnera I agree about past projects, but I think they should be relevant ones. Most of the projects I am collecting from SDG/IOT are already completed and are public items we can talk about.  I don't know how old the projects are that we pulled out??

**Comment by kelnera** [comment]
I see the point of relevance. We'll go with what's been issued and then if
someone thinks we should return something to the list, it's easy enough to
fix.

**Comment by ramereth** [comment]
I just had another realization that we should probably have links to our various github repositories to show other active projects going on. Thoughts on that?

**Comment by kelnera** [comment]
That would be easy enough to include. I think we could only safely do it
for the Open Source projects as some of the CASS projects aren't as open to
the public. But if you had specific projects in mind, if you directed me to
the repos, I could include links.

**Comment by ramereth** [comment]
@kelnera there are a lot of public repositories on the cass org so I think its safe enough to add.

So I'd recommend we add the following links on the page:

* https://github.com/osu-cass
* https://github.com/osuosl
* https://github.com/osuosl-cookbooks
