### ISSUE TITLE
Turn Sidebar from Theme to Content

### ISSUE THREAD

**Issue by kelnera** [osu-cass/cass-pelican#93]
@athai @alxngyn @subnomo @leian7 @Kennric There's another change with the sidebar. Turns out, this is where they want announcements to go. I don't want to have to bug you guys every single time an announcement needs to go in the sidebar, so we need to set it up so I can access at least part of the sidebar to add text, graphics, and links. This needs to be available for when we advertise the Friends and Family Reception.

Deadline: Friday 9/23

**Comment by subnomo** [comment]
I *believe* this was solved by osuosl/dougfir-pelican-theme#56. Can this be closed?

**Comment by athai** [comment]
Fixed by #97 and https://github.com/osuosl/dougfir-pelican-theme/pull/56
